### PR TITLE
Feature/GDEV-190

### LINKED ISSUE #16: Static file is not packaged correctly
The static JSON file [send_notification.json](https://github.com/ghga-de/sandbox-notification/blob/dev/sandbox_notification/schemata/send_notification.json) must probably be included somewhere in the `setup.cfg` file.

### PR DESCRIPTION
**Pull request by ac-jorellanaf**
Hopefully this fixes the deployment issues.

### CODE REVIEW

**Review by walzph — APPROVED** [review]

**Comment by walzph** [comment]
I think we need the same thing here: https://github.com/ghga-de/sandbox-storage/issues/40
@ac-jorellanaf can you look into that as well?

**Review by walzph — CHANGES_REQUESTED** [review]
Can you double check if using package_data instead of the MANIFEST.in file is correct here?
The inner workings differ between using sdist and bdist
https://stackoverflow.com/questions/7522250/how-to-include-package-data-with-setuptools-distutils

**Comment by ac-jorellanaf** [comment]
Well, the MANIFEST.in did not work, but package_data did. 🤷‍♂️

**Comment by lkuchenb** [comment]
I think the universal way is `MANIFEST.in` + `include_package_data=True` (which is already set) [1]

[1] https://setuptools.readthedocs.io/en/latest/userguide/datafiles.html

**Comment by lkuchenb** [comment]
I've added a working `MANIFEST.in` file

**Review by walzph — APPROVED** [review]

**Pull request merged**
